export const escapeHTML = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
export function buildPresentationHTML({ title, subtitle = '', views = [], headers = ['Specification', 'Value'], rows = [], note = '', config }) {
  const safeViews = views.filter(view => /^data:image\/(jpeg|png);base64,[a-z\d+/=]+$/i.test(view.image));
  const editable = config ? `<a href="data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify({ version: 1, config }))}" download="trailer-design.json">Download editable design</a>` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(title)}</title><style>
    *{box-sizing:border-box}body{margin:0;background:#f2f4f7;color:#18212d;font:14px system-ui,sans-serif}main{max-width:1100px;margin:30px auto;padding:32px;background:white;border-radius:12px}h1{margin:0;font-size:28px}p{line-height:1.6;color:#526173}.eyebrow{letter-spacing:.15em;font-size:11px;color:#946116;margin-bottom:10px}.views{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:25px 0}figure{margin:0;break-inside:avoid}figure img{display:block;width:100%;border-radius:8px;background:#eef0f3}figcaption{font-weight:600;padding:8px 0}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:9px 10px;border-bottom:1px solid #dbe1e8;text-align:left;vertical-align:top}thead{background:#edf1f5}.note{margin-top:22px;padding:12px;background:#fff6e5;border-left:3px solid #d19b3c;font-size:12px}button{border:0;background:#172230;color:white;border-radius:6px;padding:10px 16px;cursor:pointer}.tools{display:flex;justify-content:flex-end;margin-bottom:20px}footer{margin-top:24px;color:#64748b;font-size:11px}@media(max-width:600px){main{margin:0;padding:18px;border-radius:0}.views{grid-template-columns:1fr}th,td{padding:8px 5px;font-size:11px}}@media print{@page{margin:12mm}body{background:white}main{margin:0;padding:0;max-width:none}.tools{display:none}.views{gap:10px;margin:16px 0}table{font-size:11px}th,td{padding:6px 8px}figure img{max-height:240px;object-fit:contain}tr{break-inside:avoid}.note{break-inside:avoid}}
    .tools{gap:16px;align-items:center;flex-wrap:wrap}.tools a{color:#34465d;font-weight:600}@media print{h1{font-size:22px}.views{margin:12px 0}.views img{max-height:150px}figcaption{font-size:11px;padding:5px 0}table{font-size:10px}th,td{padding:5px 7px}p{font-size:11px}.note{font-size:10px;margin-top:15px}footer{margin-top:12px}}
    </style></head><body><main><div class="tools">${editable}<button onclick="window.print()">Print / Save as PDF</button></div><div class="eyebrow">PRO-TRAILER 3D · DESIGN STUDY</div><h1>${escapeHTML(title)}</h1><p>${escapeHTML(subtitle)}</p><div class="views">${safeViews.map(view => `<figure><img src="${view.image}" alt="${escapeHTML(view.label)}"><figcaption>${escapeHTML(view.label)}</figcaption></figure>`).join('')}</div><table><thead><tr>${headers.map(header => `<th>${escapeHTML(header)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${escapeHTML(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="note">${escapeHTML(note)}</p><footer>Generated ${escapeHTML(new Date().toISOString().slice(0, 10))} · Visualization meshes and illustrative estimates. Keep the design JSON for an editable copy.</footer></main></body></html>`;
}
